name: CI
on: [push]
jobs:
  python-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        python-version: [ '3.8' ]
        toxenv: [django32, quality ]
    steps:
      - uses: actions/checkout@v2
        continue-on-error: true
      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: browser-actions/setup-geckodriver@latest

      - name: Set up test environment
        run: |
          sudo apt-get install xvfb
          export BOTO_CONFIG=/dev/null

      - name: Install Requirements
        run: |
          pip install -r requirements/django.txt
          pip install -r requirements/ci.txt
          pip install -r requirements/test.txt
      - name: Run Tests
        run: xvfb-run --server-args=-ac -- tox -e ${{ matrix.toxenv }}
